path_1per_data:
path_1per_influencers:
path_1per_mapping:
path_1per_metadata:
path_1per_image:

path_full_data:
path_full_influencers:
path_full_mapping:
path_full_metadata:
path_full_image:

path_data:
path_influencers:
path_mapping:
path_metadata:
path_image:

image_categories:

model_detection:
threshold_detection:

