path_1per_data:
  './data/raw_1percent'
path_1per_influencers:
  './data/raw_1percent/influencers.txt'
path_1per_mapping:
  './data/raw_1percent/JSON-Image_files_mapping.txt'
path_1per_metadata:
  './data/raw_1percent/Post_metadata_(JSON files)/info'
path_1per_image:
  './data/raw_1percent/Post_images_(JPG_files)/posts_image/image'

path_full_data:
  './data/raw'
path_full_influencers:
  './data/raw/influencers.txt'
path_full_mapping:
  './data/raw/JSON-Image_files_mapping.txt'
path_full_metadata:
  './data/raw/Post metadata_(JSON_files)/info/'
path_full_image:
  './data/raw/Post_images_(JPG_files)/posts_image/image/'

path_data:
  './data/raw_1percent'
path_influencers:
  './data/raw_1percent/influencers.txt'
path_mapping:
  './data/raw_1percent/JSON-Image_files_mapping.txt'
path_metadata:
  './data/raw_1percent/Post_metadata_(JSON_files)/info'
path_metadata_popular:
  './data/raw_1percent/Post_metadata_(JSON_files)/popular'
path_image:
  './data/raw_1percent/Post_images_(JPG_files)/posts_image/image'
path_keypoints_2d_1person:
  './data/raw_1percent/Keypoints/pose_estimation_2d/1_person'
path_keypoints_3d_1person:
  './data/raw_1percent/Keypoints/pose_estimation_3d/1_person'
path_people_mapping:
  './data/raw_1percent/photo_people_mappping_05.txt'

image_categories:
  ['fashion', 'other', 'pet', 'family', 'beauty', 'interior', 'fitness', 'travel', 'food']

JointsCoCo2D:
  NOSE: 0
  LEFT_EYE: 1
  RIGHT_EYE: 2
  LEFT_EAR: 3
  RIGHT_EAR: 4
  LEFT_SHOULDER: 5
  RIGHT_SHOULDER : 6
  LEFT_ELBOW: 7
  RIGHT_ELBOW: 8
  LEFT_HAND: 9
  RIGHT_HAND: 10
  LEFT_HIP: 11
  RIGHT_HIP: 12
  LEFT_KNEE: 13
  RIGHT_KNEE: 14
  LEFT_FOOT: 15
  RIGHT_FOOT: 16
coco_head_points:
  [0, 1, 2, 3, 4]
coco_connections:
  [[0, 1], [1, 3], [0, 2], [1, 2], [2, 4], [4, 6], [3, 5], [6, 5], [5, 11],[11, 12], [12, 6], [6, 8], [8, 10], [5, 7], [7, 9], [12, 14], [14, 16], [11, 13], [13, 15]]
coco_angles:
  [[12,14,16], [11,13,15], [11,12,14], [12,11,13], [6,12,11], [5,11,12], [10,8,6], [9,7,5], [12,6,8], [11,5,7], [12,6,5] ,[11,5,6]]
coco_base_connestion:
  [5,6]

JointsHuman3D:
  LOWER_SPINE: 0
  RIGHT_HIP: 1
  RIGHT_KNEE: 2
  RIGHT_FOOT: 3
  LEFT_HIP: 4
  LEFT_KNEE: 5
  LEFT_FOOT: 6
  UPPER_SPINE: 7
  THROAT: 8
  NOSE: 9
  FORHEAD: 10
  LEFT_SHOULDER: 11
  LEFT_ELBOW: 12
  LEFT_HAND: 13
  RIGHT_SHOULDER: 14
  RIGHT_ELBOW: 15
  RIGHT_HAND: 16
human36_head_points:
  [9, 10]
human36_connections:
  [[0, 1], [1, 2], [2, 3], [0, 4], [4, 5], [5, 6], [0, 7], [7, 8], [8, 11], [11, 12], [12, 13], [8, 14], [14, 15], [15, 16], [8, 9], [9, 10]]
human36_angles:
  [[1,2,3], [4,5,6], [0,1,2], [0,4,5], [7,0,1], [7,0,4], [8,7,0], [8,11,12], [8,14,15], [11,8,7], [14,8,7] ,[8,9,10], [7,8, 9]]
human36_base_connestion:
  [11,14]

# should be removed and replaced n visualizer by coco_angles
angles:
  [[12,14,16], [11,13,15], [11,12,14], [12,11,13], [6,12,11], [5,11,12], [10,8,6], [9,7,5], [12,6,8], [11,5,7], [12,6,5] ,[11,5,6]]
base_connestion:
  [5,6]


model_detection:
  './models/detection/yolov8n.pt'
threshold_detection:
  - 0.5
